"""Utility modules for MTG-Causal-RL.

This package contains visualization, CLI display, HTML report, and interactive utilities.
"""

from mtg.utils.cli_display import (
    PHASES,
    PRIORITY_PHASE_NAMES,
    GameStateSnapshot,
    PlayerState,
    TrainingDisplay,
    TrainingMetrics,
    console,
    format_mana_cost,
    print_divider,
    print_evaluation_results,
    print_game_state,
    print_instant_response,
    print_logo,
    print_mulligan_state,
    print_play_draw_selection,
    print_priority_window,
    print_stack_item,
    print_turn_summary,
)
from mtg.utils.html_report import (
    CardInfo,
    GameAction,
    GameRecorder,
    GameReplay,
    InitialGameState,
    MulliganInfo,
    ReplayStateSnapshot,
    TurnSummary,
    generate_html_report,
    load_replay_json,
    save_replay_json,
)
from mtg.utils.interactive import (
    EvaluationConfig,
    GameplayConfig,
    TrainingConfig,
    confirm_config,
    create_output_directory,
    discover_trained_models,
    format_duration,
    get_archetype_info,
    get_available_agents,
    get_available_archetypes,
    print_section_header,
    prompt_agent_selection,
    prompt_deck_selection,
    prompt_evaluation_config,
    prompt_gameplay_config,
    prompt_training_config,
)
from mtg.utils.visualization import (
    COLORS,
    PUBLICATION_STYLE,
    apply_publication_style,
    create_comparison_bar,
    create_generalization_heatmap,
    create_learning_curve,
    create_scm_diagram,
)

__all__ = [
    # Visualization
    "apply_publication_style",
    "create_learning_curve",
    "create_comparison_bar",
    "create_scm_diagram",
    "create_generalization_heatmap",
    "COLORS",
    "PUBLICATION_STYLE",
    # CLI Display
    "console",
    "print_logo",
    "print_divider",
    "TrainingDisplay",
    "TrainingMetrics",
    "print_evaluation_results",
    "print_game_state",
    "print_mulligan_state",
    "print_turn_summary",
    "print_play_draw_selection",
    "print_instant_response",
    "print_priority_window",
    "print_stack_item",
    "PlayerState",
    "GameStateSnapshot",
    "PHASES",
    "PRIORITY_PHASE_NAMES",
    "format_mana_cost",
    # HTML Report
    "CardInfo",
    "GameAction",
    "ReplayStateSnapshot",
    "MulliganInfo",
    "InitialGameState",
    "TurnSummary",
    "GameReplay",
    "GameRecorder",
    "generate_html_report",
    "save_replay_json",
    "load_replay_json",
    # Interactive
    "TrainingConfig",
    "EvaluationConfig",
    "GameplayConfig",
    "discover_trained_models",
    "get_available_agents",
    "get_available_archetypes",
    "get_archetype_info",
    "prompt_agent_selection",
    "prompt_deck_selection",
    "prompt_training_config",
    "prompt_evaluation_config",
    "prompt_gameplay_config",
    "confirm_config",
    "create_output_directory",
    "format_duration",
    "print_section_header",
]
